apiVersion: v1
kind: Service
metadata:
  name: backend-model-service
spec:
  selector:
    app: multi-container-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort