---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: "gfgdeployment"
spec: 
  replicas: 3
  selector:
    matchLabels:
      dc: "In"
  template:
    metadata:
      name: "mypod"
      labels:
        dc: "In"
    spec:
      containers:
      - name: "myos"
        image: jinny1/snakegame:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000 

---

apiVersion: v1
kind: Service
metadata:
  name: "mygfgservice"
spec:
  selector:
    dc: "In"
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 31933
  type: LoadBalancer
