apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-deployment
  template:
    metadata:
      labels:
        app: model-deployment
    spec:
      containers:
      - name: app
        image: jinny1/model-expose-app:v1
        ports:
        - containerPort: 5000
      - name: backend-model
        image: jinny1/weather-db-ingestion-model:v1

      - name: database
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "weather_data"
        - name: POSTGRES_PASSWORD
          value: "mysecretpassword"
