apiVersion: v1
kind: Service
metadata:
  name: model-service
spec:
  selector:
    app: model-deployment
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      NodePort: 31933
  type: NodePort