- name: Run Command Playbook
  hosts: k8s-master
  become: true  # Run tasks with sudo

  tasks:
    - name: Copy the deploment.yml file to Target Node
      copy:
        src: ../modeldeployment.yml
        dest: deployment.yml
    - name: Copy the service to the Target Node
      copy:
        src: ../service.yml
        dest: service.yml

    - name: Check if Deployment exists
      command: "kubectl get deployment model-deployment"
      ignore_errors: true
      register: deployment_check

    - name: Run Deployment or Rollout
      command: "kubectl create -f deployment.yml"
      when: deployment_check.rc != 0  # Deployment doesn't exist
      ignore_errors: true

    - name: Rollout Deployment
      command: "kubectl rollout restart deployment model-deployment"
      when: deployment_check.rc == 0  # Deployment exists
      ignore_errors: true
      
    - name: "Get the third IP address"
      shell: hostname -I | awk '{print $2}'
      register: third_ip

    - name: Start Service
      command: "kubectl apply -f service.yml"
    - name: Create socat service file
      copy:
        dest: /etc/systemd/system/socat.service
        content: |
          [Unit]
          Description=Socat TCP forwarder
          After=network.target

          [Service]
          Type=simple
          ExecStart=/usr/bin/socat TCP4-LISTEN:5000,fork TCP4:{{ third_ip.stdout }}:31933
          Restart=always
          User=nobody

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable and start socat service
      systemd:
        name: socat
        enabled: true
        state: started